version: 2

registries:
  ecr-public:
    type: docker-registry
    url: public.ecr.aws
    replaces-base: true

updates:
  - package-ecosystem: "docker"
    directories:
      - "/docker"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    open-pull-requests-limit: 10
    commit-message:
      prefix: "build"
      include: "scope"
    groups:
      docker:
        patterns: ["*"]
    registries:
      - ecr-public
