version: 2
updates:
  - package-ecosystem: "docker"
    directories:
      - "/docker"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 5
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    open-pull-requests-limit: 10
    commit-message:
      prefix: "build"
      include: "scope"
    groups:
      docker:
        patterns: ["*"]
