name: 'Semantic Release'

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  semantic-release:
    runs-on: ubuntu-22.04
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create
        run: echo "TEST" >> test.txt

      - name: Create
        uses: ./.github/actions/semantic
        with:
          no-checkout: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          release-assets: |
            gradle/wrapper/gradle-wrapper.properties
            build.gradle
            test.txt
          tag-prefix: 'test-v'