name: 'Semantic Release'

on:
  pull_request:
    branches: [ "main" ]


jobs:
  semantic-release:
    uses: ./.github/workflows/reusable-semantic.yml
    with:
      environment: dev
      release-assets: |
        gradle/wrapper/gradle-wrapper.properties
        build.gradle