name: "Test job"

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    outputs:
      triggered:
        description: "Was the job triggered"
        value: ${{ jobs.test-job.outputs.triggered }}
jobs:
  test-job:
    name: 'Test job'
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    outputs:
      triggered: ${{ steps.test-step.outputs.triggered }}
    steps:
      - name: Test step
        id: test-step
        run: |
          echo 'Test step executed'
          echo "triggered=true" >> $GITHUB_OUTPUT
          echo 'CONCLUSION=${{ env.WORKFLOW_CONCLUSION }}'
          exit 1
#          echo "OUTPUT=${{ steps. }}" >> $GITHUB_OUTPUT
