name: "Test job"

on:
  workflow_call:
    inputs:
      environment:
        required: false
        type: string
jobs:
  test-job:
    name: 'Test job'
    runs-on: ubuntu-latest
    steps:
      - name: Test step
        run: echo 'Test step executed'