name: "Test job"

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
jobs:
  test-job:
    name: 'Test job'
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Test step
        run: |
          echo 'Test step executed'
          echo "TRIGGERED=true" >> $GITHUB_OUTPUT
          echo 'CONCLUSION=${{ env.WORKFLOW_CONCLUSION }}'
#          echo "OUTPUT=${{ steps. }}" >> $GITHUB_OUTPUT
