name: "Test job"

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    outputs:
      triggered:
        description: "Was the job triggered"
        value: ${{ jobs.test-job.outputs.triggered }}
      status_ok:
        description: "Status ok"
        value: ${{ jobs.test-job.outputs.status_ok }}
jobs:
  test-job:
    name: 'Test job'
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    outputs:
      triggered: ${{ steps.set-outputs.outputs.triggered }}
      status_ok: ${{ steps.set_status.outputs.status_ok }}
    steps:
      - name: Set GitHub outputs
        id: set-outputs
        run: |
          echo 'Test step executed'
          echo "triggered=true" >> $GITHUB_OUTPUT
          echo 'CONCLUSION=${{ env.WORKFLOW_CONCLUSION }}'
          echo "${{ github.event_name }}"
          echo "${{ github.head_ref }}"
          echo "${{ github.ref_name }}"
#          exit 1
#          echo "OUTPUT=${{ steps. }}" >> $GITHUB_OUTPUT
      - name: 'Test step 2'
        id: 'test-step'
        run: |
            echo 'Second step executed'
            exit 1
      - name: Determine Status
        if: ${{ always() }}
        id: set_status
        run: |
          echo "status_ok=${{ ( job.status == 'success' || (job.status == 'failure' && steps.set-outputs.outputs.triggered == 'true')) }}" >> $GITHUB_ENV
          echo "${{ job.status }}"